version: "2.4"

services:
  odoo:
    extends:
      file: common.yaml
      service: odoo
    restart: unless-stopped
    env_file:
      - .docker/odoo.env
      - .docker/db-access.env
    environment:
      DB_FILTER: "^prod"
      DOODBA_ENVIRONMENT: "${DOODBA_ENVIRONMENT-prod}"
      INITIAL_LANG: "en_US"
      PYTHONOPTIMIZE: ""
    volumes:
      - ./odoo/custom:/opt/odoo/custom:rw,z
      - ./odoo/auto:/opt/odoo/auto:rw,z
      - /opt/odoo/custom/src/odoo
    depends_on:
      - db
    networks:
      mynetwork:
        ipv4_address: 172.20.0.10
    labels:
      doodba.domain.main: ""

  db:
    extends:
      file: common.yaml
      service: db
    env_file:
      - .docker/db-creation.env
    environment:
      CONF_EXTRA: |
        max_connections = 100
        shared_buffers = 2GB
        effective_cache_size = 6GB
        maintenance_work_mem = 512MB
        checkpoint_completion_target = 0.9
        wal_buffers = 16MB
        default_statistics_target = 100
        random_page_cost = 1.1
        effective_io_concurrency = 200
        work_mem = 5242kB
        min_wal_size = 1GB
        max_wal_size = 4GB
        max_worker_processes = 4
        max_parallel_workers_per_gather = 2
        max_parallel_workers = 4
        max_parallel_maintenance_workers = 2
    restart: unless-stopped
    networks:
      mynetwork:
        ipv4_address: 172.20.0.11

  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    volumes:
      - nginx:/etc/nginx/
    networks:
      mynetwork:
        ipv4_address: 172.20.0.12
        
  mkdocs:
    image: polinux/mkdocs:1.2.3
    restart: always
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      LIVE_RELOAD_SUPPORT: "true"
      FAST_MODE: "true"
      DOCS_DIRECTORY: "/mkdocs"
    volumes:
      - /opt/skyviv-docs:/mkdocs
    networks:
      mynetwork:
        ipv4_address: 172.20.0.13

networks:
  mynetwork:
    driver_opts:
      encrypted: 1
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  filestore:
  db:
  nginx:
